version: '3'
services:
  browser:
    # headless version
    #image: selenium/standalone-chrome
    
    # the debug version lets you see/interact via VNC
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
      - "4444:4444"
  ruby:
    build: .
    volumes:
      - .:/app
    depends_on: 
      - browser
